// File generated by: dart run flutterfire_cli:flutterfire configure
// Or fill in your Firebase project values from Firebase Console → Project settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJwAagoUrR0_fSx9vOSHtFKFGr6m4MoJY',
    appId: '1:222737206616:android:4c624b46d06953e79d292d',
    messagingSenderId: '222737206616',
    projectId: 'greenhaul-488aa',
    storageBucket: 'greenhaul-488aa.firebasestorage.app',
  );
}
